# Documentation about Garden projects can be found at https://docs.garden.io/using-garden/projects
# Reference for Garden projects can be found at https://docs.garden.io/reference/project-config

apiVersion: garden.io/v1
kind: Project
name: gardentest

defaultEnvironment: local
variables:  
  userNamespace: rb-namespace

environments:
  - name: local
    defaultNamespace: ${var.userNamespace}
    variables:
      hostname: local.app.garden

providers:
  - name: local-kubernetes
    environments: [local]