apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
    # annotations:
    #   volume.beta.kubernetes.io/storage-class: managed-premium # <!-- this is azure, what storage class for local kubernetes
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi   